dist: xenial
language: shell  # MEANINGLESS!
services:
  - docker
env:
  global:
    - EMACS_IMAGE=silex/emacs:26.1-alpine
install:
  - docker pull "$EMACS_IMAGE"
before_script:
  - env | grep -i travis | sort
script:
  - docker run --rm -v "$PWD:/mnt" -w /mnt "$EMACS_IMAGE" emacs --batch -l hugo-export.el
after_success:
#   - ./script/push_changes_to_github.sh
