baseURL = "https://clever-murdock-3ab329.netlify.com/"
languageCode = "ja-JP"
title = "備忘録"
theme = "hugo-octopress"

disableAliases = true

[params]
  # This text appears in site header under website title
  subtitle = "いろいろ忘れないためのブログ"
